#!/bin/bash

set -e

setup_all() {
  sudo apt -y update && sudo apt -y upgrade
  sudo apt -y install build-essential
  rm -rf $HOME/.vim
}

setup_git() {
  sudo apt -y install git
  wget -O $HOME/.gitconfig https://raw.githubusercontent.com/kazimir-malevich/dotfiles/master/.gitconfig
}

setup_neovim() {  
  wget https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
  sudo tar zxvf nvim-linux64.tar.gz -C /opt 
  sudo ln -s /opt/nvim-linux64/bin/nvim /usr/local/bin/nvim
  mkdir -p ~/.config/nvim/
  wget -O $HOME/init.vim https://raw.githubusercontent.com/kazimir-malevich/dotfiles/master/init.vim
  # install vim-plug
  sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
}

setup_bash() {
if grep -q "alias vi='vim'" ~/.bashrc; then return 0; fi

cat <<EOT >> $HOME/.bashrc

alias vi='vim'
alias nv='nvim'
alias ..="cd .."
alias ll='ls -lahF'
alias cl='clear'
alias py='python'

export PATH=~/.npm-global/bin:$PATH

EOT
}

setup_js() {
  dir=~/.npm-global
  sudo apt -y install nodejs npm
  [[ -d $dir ]] || mkdir $dir
  npm config set prefix $dir
  npm install -g eslint
  npm install -g prettier
}

setup_jvm() {
  sudo apt install default-jdk
  sudo apt-get install openjdk-11-source
  
 # Using Coursier and https://github.com/scala/scala-seed.g8
}

setup_misc() {
  sudo apt -y install tree
  npm install -g tldr
}

teardown_all() {
  sudo apt -y autoremove
}

setup_all
setup_git
setup_js
setup_neovim
setup_bash
setup_jvm
setup_misc
teardown_all
