#!/bin/bash

set -e

setup_all() {
  sudo apt -y update && sudo apt -y upgrade
  sudo apt -y install build-essential
  rm -rf $HOME/.vim
}

setup_git() {
  sudo apt -y install git
  wget -O $HOME/.gitconfig https://raw.githubusercontent.com/kazimir-malevich/dotfiles/master/.gitconfig
}

setup_vim() {
  plugins_start_dir="$HOME/.vim/pack/plugins/start/"

  sudo apt -y install vim
  wget -O $HOME/.vimrc https://raw.githubusercontent.com/kazimir-malevich/dotfiles/master/.vimrc

  mkdir -p $plugins_start_dir && cd $plugins_start_dir

  declare -a plugins

  plugins=("tpope/vim-commentary" "ctrlpvim/ctrlp.vim.git" \
    "sheerun/vim-polyglot" "dense-analysis/ale")

  cd $plugins_start_dir

  for i in ${plugins[@]}; do
    git clone "https://github.com/${i}"
  done

}

setup_bash() {
  if grep -q "alias vi='vim'" ~/.bashrc; then return 0; fi

  cat <<EOT >> $HOME/.bashrc

  alias vi='vim'
  alias ..="cd .."
  alias ll='ls -lahF'
  alias cl='clear'
  alias py='python'

  EOT
}

setup_rust() {
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  source $HOME/.cargo/env

  # rust-analyzer
  mkdir ~/bin
  curl -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz | gunzip -c - > ~/bin/rust-analyzer
  chmod +x ~/bin/rust-analyzer

  # needed for cargo check
  sudo apt install libssl-dev pkg-config
}

setup_js() {
  sudo apt -y install nodejs yarn
}

setup_misc() {
  sudo apt -y install tree
  sudo apt install tldr && tldr --update
}

teardown_all() {
  sudo apt -y autoremove
}

setup_all
setup_git
setup_vim
setup_bash
setup_rust
setup_misc
teardown_all
